### ISSUE TITLE
question about VAE model

### ISSUE THREAD

**Issue by ooooooover** [eth-siplab/Finding_Order_in_Chaos#1]
Thank you for your excellent work, I have a question about the VAE model, I don't quite understand what role he plays, it doesn't seem to be explained in the paper. Looking forward to your answer.

**Comment by Berken-demirel** [comment]
Hi @ooooooover, 
Thank you for your kind words and for your interest in our work. The role of the VAE is detailed in Proposition 3.2 and the accompanying paragraph in the paper. Additionally, its contribution to the overall method is examined in the ablation studies presented in Section 5.1, where it is referred to as "w/o Aug. Degree."

I hope this clarifies your question. Please let me know if there are any other questions or if you need further explanation.
