### ISSUE TITLE
Question About DeepConvLSTM 

### ISSUE THREAD

**Issue by alexkaravos** [eth-siplab/Finding_Order_in_Chaos#2]
Why are the convolutional layers in DCL 2D given that the kernal size is (size,1)? Does this produce different results than 1D Conv layers like in the FCN? 

Is this the recommended backbone for SimClr frameworks?

**Comment by Berken-demirel** [comment]
Hi @alexkaravos ,

We used several baselines and mainly adopt them from the previous work as in [repo](https://github.com/Tian0426/CL-HAR/blob/main/models/backbones.py). While we observed the best performance with the DCL, the 1D-ResNet and FCN models also gave comparable results for some datasets. For the DCL architecture, although we adopted the exact architecture, the 1D Conv (as in the FCN) should give the same performance though.

**Comment by alexkaravos** [comment]
Thanks!
