### ISSUE TITLE
Request for IEEE SPC12 and IEEE SPC22 Dataset

### ISSUE THREAD

**Issue by yiminzme** [eth-siplab/Finding_Order_in_Chaos#3]
Dear Author of this paper,

I hope this message finds you well. I am currently working on a project that aims to extend the research presented in your paper. To achieve this, we heavily rely on the datasets referenced in your paper, specifically the IEEE SPC12 and IEEE SPC22 datasets. Unfortunately, we have been unable to locate these datasets through the usual channels and were wondering if you could kindly provide a copy or guide us on where we might obtain them.

Your research has been incredibly valuable to our work, and access to these datasets would greatly enhance the progress of our project. Any assistance you could offer would be immensely appreciated.

Thank you very much for your time and help.

Best regards,
Yimin Zheng

**Comment by Berken-demirel** [comment]
Hi @yiminzme ,

We accessed the SPC dataset using the [paper ](https://ieeexplore.ieee.org/document/8119878) and their [repo](https://github.com/AlessandraGalli/PPG). Please let me know if you can access it, otherwise I can also try to provide the files we used.

**Comment by yiminzme** [comment]
Thanks a lot for pointing that out! We are able to access them ;-)
