### ISSUE TITLE
Request for IEEE SPC12/IEEE SPC22 Dataset

### ISSUE THREAD

**Issue by wzhSteve** [eth-siplab/Finding_Order_in_Chaos#6]
I'm trying to replicate your work. At the time of reproduction, I found that the link you provided in the[ issue#3](https://github.com/eth-siplab/Finding_Order_in_Chaos/issues/3) about IEEE SPC12 and the IEEE SPC22 dataset, but I did not run the project successfully on these datasets after I processed them. I would be grateful if it is convenient for you to provide the dataset files you use. My email address is wzhrslh@gmail.com. Thank you very much for your help and sharing.

**Comment by Berken-demirel** [comment]
Hi @wzhSteve.

I have shared the processed data with you. For future reference, it would be helpful if you could provide some details about your runs, such as any errors or the results you obtained with specific commands. And, please let me know if any issues persist.
