### ISSUE TITLE
Heart Rate Prediction Dataset Question and Access

### ISSUE THREAD

**Issue by sml-hash** [eth-siplab/Finding_Order_in_Chaos#7]
Hello, thank you very much for opensourcing your work. This is excellent and very interesting research! I just have a quick question - I noticed that for the heart rate prediction datasets (IEEE SPC12, SPC22, and Dalia), your code seems to only be using one of the PPG channels. DaLiA only provides on PPG channel, but the IEEE datasets provide two channels, as far as I understand. Is there a reason why you're only using one of those channels? Or am I missing something?

Also, may I ask where I can find the IEEE SPC12/SPC22 datasets? I'm not able to find them on the website linked in your repo. Again, thank you so much!

**Comment by Berken-demirel** [comment]
Hi @sml-hash,

For datasets with multiple channels, we averaged them into a single channel, as you can see from the [scripts](https://github.com/eth-siplab/Finding_Order_in_Chaos/blob/141b2b9f51543a267a86312b19238936853be0c5/raw_data_process/SPCs%26Dalia/SPCs/data_prep_IEEETrain_cont.m#L22C1-L24C45) too. This is a common pre-processing step in PPG based HR detection and we just followed the previous techniques.


You might find this [issue](https://github.com/eth-siplab/Finding_Order_in_Chaos/issues/3#issuecomment-2210544622) useful to find the IEEE SPC datasets. Let me know if you have any trouble finding it!
